### PR TITLE
improve search by showing highlighted snippet and link to relevant parts of TOC

### PR DESCRIPTION
**Pull request by mickhansen**

### CODE REVIEW

**Comment by mickhansen** [comment]
image

**Comment by sgryt** [comment]
If I 
1: search for response_type ard click on the first hit
2: search again  for response_mode
then I can't close the search box by clicking the link to the first hit (same page as returned in 1).

**Comment by sgryt** [comment]
Can we add a keyboard shortcut to focus on the search box ? Like `/` in gmail does.

**Comment by mickhansen** [comment]
> Can we add a keyboard shortcut to focus on the search box ? Like `/` in gmail does.

Sure, not sure how users will discover it though?

**Comment by mickhansen** [comment]
> If I 1: search for response_type ard click on the first hit 2: search again for response_mode then I can't close the search box by clicking the link to the first hit (same page as returned in 1).

Hmm yeah, it closes when we navigate and we don't do that when we're already on the same page, not exclusive to this PR but will see if I can address it.

**Comment by sgryt** [comment]
> > If I 1: search for response_type ard click on the first hit 2: search again for response_mode then I can't close the search box by clicking the link to the first hit (same page as returned in 1).
> 
> Hmm yeah, it closes when we navigate and we don't do that when we're already on the same page, not exclusive to this PR but will see if I can address it.

Let us postpone to another PR if it is tricky to fix.

**Comment by mickhansen** [comment]
> > > If I 1: search for response_type ard click on the first hit 2: search again for response_mode then I can't close the search box by clicking the link to the first hit (same page as returned in 1).
> > 
> > 
> > Hmm yeah, it closes when we navigate and we don't do that when we're already on the same page, not exclusive to this PR but will see if I can address it.
> 
> Let us postpone to another PR if it is tricky to fix.

Think it's fixed with the latest commit

**Pull request merged**
