### PR TITLE
validate credentials for the graphql explorer/examples

### PR DESCRIPTION
**Pull request by mickhansen**
https://trello.com/c/bGRgT3rr/300-when-asking-for-crendentials-at-the-interactive-demo-they-should-be-validated-you-can-enter-wrong-credentials-and-be-shown-to-in

### CODE REVIEW

**Comment by sgryt** [comment]
@mickhansen Review blocked by the current error on manage.criipto.io (not sure I have signature API credentials lying around for test, but can't create a fresh set before the mgmt dashboard works again).

**Comment by runefs** [comment]
The credentials are verified (pun intended) when using the examples but the issue is the same for the explorer

**Comment by mickhansen** [comment]
> The credentials are verified (pun intended) when using the examples but the issue is the same for the explorer

Are you referring to this explorer: https://signatures-api.criipto.com/v1/explorer ?
It's a seperate codebase so not related to this PR.

**Comment by runefs** [comment]
> 

Check! It is however related to the same board on Trello (I've posted a similar comment there)

**Comment by mickhansen** [comment]
> > 
> 
> Check! It is however related to the same board on Trello (I've posted a similar comment there)

That makes sense! But if we could get this PR merged I think it's definitely still an improvement :)

**Pull request merged**
